sudo: required

language: python
python:
  - "3.6"
  - "2.7"

services:
  - docker

before_install:
  - docker version
  - pip install docker-compose
  - docker-compose -f docker-compose-test-server.yml up -d
  
script:
  - docker ps
  - pytest tests/tests.py
