sudo: required

language: python
python:
  - "3.6"
  - "2.7"

services:
  - docker

before_install:
  - docker version
  - pip install docker-compose
  - cd tests/testserver
  - docker-compose up -d
  - docker ps
  
script:
  - cd ../..
  - pytest tests/tests.py
