sudo: required

language: python
python:
  - "3.6"
  - "2.7"

services:
  - docker

before_install:
  - docker version
  - pip install docker-compose
  - docker-compose -f docker-compose-test-server.yml up -d
  
script:
  - docker ps
  - until curl http://localhost:3000/api/v1/info; do sleep 5; echo "waiting for Rocket.Chat server to start"; done
  - pytest tests/tests.py
